### ISSUE TITLE
French words

### ISSUE THREAD

**Issue by NoMaxLand** [Balatzar/react-survey#2]
There is french words in demonstration and in the documentation (Oui and Non)

![selection_045](https://user-images.githubusercontent.com/11667391/30003068-7921be7e-90b8-11e7-8669-c6a978a20dcf.png)

**Comment by Balatzar** [comment]
Thanks, fixed in https://github.com/Balatzar/react-survey/commit/4c346337731c5986a341056f1f9b147bec678829
