### ISSUE TITLE
I can't close Survey on ending

### ISSUE THREAD

**Issue by NoMaxLand** [Balatzar/react-survey#3]
I can't close survey modal when I finished.

![selection_047](https://user-images.githubusercontent.com/11667391/30003071-860b661c-90b8-11e7-93eb-f89141116f8f.png)

**Comment by Balatzar** [comment]
Thank you! It is fixed with https://github.com/Balatzar/react-survey/commit/29e45a6b6f720df52d5a47f7b02e834f6071719b
